package POJO;
// Generated Oct 21, 2020 8:36:45 AM by Hibernate Tools 4.3.1

import daos.DAO;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;




/**
 * OrdercancelTbl generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class OrdercancelTbl  implements java.io.Serializable {


     private Integer ordercancelId;
     private int orderId;
     private String reason;

    public OrdercancelTbl() {
    }

    public OrdercancelTbl(int orderId, String reason) {
       this.orderId = orderId;
       this.reason = reason;
    }
   
    public Integer getOrdercancelId() {
        return this.ordercancelId;
    }
    
    public void setOrdercancelId(Integer ordercancelId) {
        this.ordercancelId = ordercancelId;
    }
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    
     public void save()
    {
        OrderTbl otb = new OrderTbl();
        setReason("CANCELATION");
        DAO pdao=new DAO();
        pdao.addOrderc(this);
    }
     
     public List<OrdercancelTbl> getallrecords()
    {
        DAO pdao=new DAO();
        List<OrdercancelTbl> prod=pdao.retrieveCancel();
        return prod;
    }
     
      public void updateCancel()
    {
        OrderTbl ot = new OrderTbl();
        ot.setOrderId(orderId);
        ot.saveCancel();
        setReason("CANCELLED");
        DAO pdao=new DAO();
        pdao.updateOrderapprove(this);
    }



}


