package POJO;
// Generated Oct 21, 2020 8:36:45 AM by Hibernate Tools 4.3.1
import daos.DAO;
import javax.faces.bean.SessionScoped;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;


/**
 * VocList generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class VocList  implements java.io.Serializable {


     private Integer vocId;
     private String vocName;
     private int vocPrice;
     private int vocStock;

    public VocList() {
    }

    public VocList(String vocName, int vocPrice, int vocStock) {
       this.vocName = vocName;
       this.vocPrice = vocPrice;
       this.vocStock = vocStock;
    }
   
    public Integer getVocId() {
        return this.vocId;
    }
    
    public void setVocId(Integer vocId) {
        this.vocId = vocId;
    }
    public String getVocName() {
        return this.vocName;
    }
    
    public void setVocName(String vocName) {
        this.vocName = vocName;
    }
    public int getVocPrice() {
        return this.vocPrice;
    }
    
    public void setVocPrice(int vocPrice) {
        this.vocPrice = vocPrice;
    }
    public int getVocStock() {
        return this.vocStock;
    }
    
    public void setVocStock(int vocStock) {
        this.vocStock = vocStock;
    }
    
    public List<VocList> getbyid()
    { 
        DAO pdao=new DAO();
        List<VocList> prod=pdao.getbyID(vocId);
        vocName=prod.get(0).vocName;
        vocPrice=prod.get(0).vocPrice;
        vocStock=prod.get(0).vocStock;
        return prod;
    }




}


